// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9K_vsyay8zgN2wptunnk6ZONwv1jIUo',
    appId: '1:143561836321:web:5ee85c54cdfc9a3a9be060',
    messagingSenderId: '143561836321',
    projectId: 'adminsidechapstone',
    authDomain: 'adminsidechapstone.firebaseapp.com',
    databaseURL: 'https://adminsidechapstone-default-rtdb.firebaseio.com',
    storageBucket: 'adminsidechapstone.appspot.com',
    measurementId: 'G-JXPJQPCVE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-yK0styGFnlnarZogB8o8ftOR88HkKKg',
    appId: '1:143561836321:android:105a17316d655fd99be060',
    messagingSenderId: '143561836321',
    projectId: 'adminsidechapstone',
    databaseURL: 'https://adminsidechapstone-default-rtdb.firebaseio.com',
    storageBucket: 'adminsidechapstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_Z1-RR2gZi_qffQZBI_44SmMUJrNtGc',
    appId: '1:143561836321:ios:2f4ed2992e5fac0f9be060',
    messagingSenderId: '143561836321',
    projectId: 'adminsidechapstone',
    databaseURL: 'https://adminsidechapstone-default-rtdb.firebaseio.com',
    storageBucket: 'adminsidechapstone.appspot.com',
    iosClientId: '143561836321-7pp15mke9jdst7jelvdhe4op6fbbr0o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftresponse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_Z1-RR2gZi_qffQZBI_44SmMUJrNtGc',
    appId: '1:143561836321:ios:2f4ed2992e5fac0f9be060',
    messagingSenderId: '143561836321',
    projectId: 'adminsidechapstone',
    databaseURL: 'https://adminsidechapstone-default-rtdb.firebaseio.com',
    storageBucket: 'adminsidechapstone.appspot.com',
    iosClientId: '143561836321-7pp15mke9jdst7jelvdhe4op6fbbr0o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftresponse',
  );
}
